apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  namespace: jenkins-project
spec:
  type: LoadBalancer
  selector:
    app: jenkins
  ports:
    - name: jenkins
      port: 8080
      targetPort: 8080
    - name: jenkins-agent
      port: 5000
      targetPort: 5000
